//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public string NomePet { get; set; }
        public string Especie { get; set; }
        public string Servico1 { get; set; }
        public int ID_Servico { get; set; }
        public string Data { get; set; }
        public string Horario { get; set; }
    }
}
